### ISSUE TITLE
Scroll bug

### ISSUE THREAD

**Issue by Schweriner** [FrDH/mmenu-light#1]
There is a bug when the menue and the page are higher than the devices viewport which causes the page instead of the menue to scroll.

**Comment by xcartmods** [comment]
You can prevent the body of page scrolling while the menu is open.

`                open: function() {
                    **document.body.classList.add("overflow-y-hidden");**
                    return m.classList.add("mm--open"), o
                },
                close: function() {
                    **document.body.classList.remove("overflow-y-hidden");**
                    return m.classList.remove("mm--open"), o
                },`

CSS...
`.overflow-y-hidden { overflow-y: hidden; }`

**Comment by FrDH** [comment]
thanks, i'll do some investigating.

**Comment by FrDH** [comment]
@xcartmods Did you actually implement this fix?
If so, could you check if the page remains scrolled after opening the menu?

**Comment by xcartmods** [comment]
Yes, it worked for what I want to achieve, although I've only tested in the major browsers so far.
You can see here if you like (WIP) - http://xcartmods.com/mmenu2/light.html

I did couple other things...
- Added a close button
- Changed a||(a="Menu") TO a||(a=m.dataset.title) so that you can change the default title with data-title="Whatever"

Am just about to add a dark theme, loving it so far :)

**Comment by FrDH** [comment]
I always thought that adding `overflow: hidden` to the html or body would jump the content to the top.

**Comment by xcartmods** [comment]
Thanks for v1.0.7 (FYI, the version # is missing from the dist JS files) :)
Yes, overflow:hidden on the body seems to work fine without jumping.
I would also suggest adding pointer-events:none to the body.

Updated my demo link ^ although I'm still on v1.0.6

**Comment by FrDH** [comment]
> Changed a||(a="Menu") TO a||(a=m.dataset.title) so that you can change the default title with data-title="Whatever"
This is undocumented, but you also could have added `data-mm-title` to the main `<ul>`:
````html
<nav>
   <ul data-mm-title="My menu">
      <li><a>Home</a></li>
   </ul>
</nav>
````

**Comment by xcartmods** [comment]
Perfect, thanks Fred
