### ISSUE TITLE
IE11 Compatibility

### ISSUE THREAD

**Issue by julmot** [FrDH/mmenu-light#10]
Open the website's homepage and click on the hamburger icon => Nothing happens

https://www.mmenujs.com/mmenu-light/

In my own integration the layout is broken. Since this is very urgent for me and I get the feeling the plugin isn't really ready for production, am I right that it's an experimental thing not comparable with mmenu?

**Comment by FrDH** [comment]
I can't really think of any reason for it not to work on IE11, what have you tried to fix it?
Are there js errors?
Is there any other information you could give?

**Comment by julmot** [comment]
I might be able to provide more information if I could get the fiddle mentioned in #9 up and running.

**Comment by stl-pl** [comment]
There are 2 errors in IE11 Console:
- Syntax error: mmenu-light.js (1,949);
- Syntax error: default.html (61,43).

**Comment by FrDH** [comment]
As of the later versions, you'll need some polyfills for:
object.assign
element.closest
element.matches
element.after
element.append
element.replaceWith

and for css variables.

**Comment by stl-pl** [comment]
I added css-var-polyfill.js and some polyfills via polyfill.io and nothing has changed. Could You provide a link via https://polyfill.io/v3/url-builder/? (I just need to add this 2 scripts or there's something more?)

By the way, demo on https://mmenujs.com/mmenu-light/ does not work at all (iframe example).

**Comment by FrDH** [comment]
I set the computer options (for the next release) to ES6, should help. Thank you for bringing the broken example to my attention, I’ll update it later on.

**Comment by FrDH** [comment]
Also, I’ll add fallbacks for the CSS variables.

**Comment by FrDH** [comment]
Give version 2.2.0 a try.
It is teanspiled back to es5, comes with a polyfills file and has fallbacks for css variables.

**Comment by stl-pl** [comment]
Unfortunately menu still does not work. Now I only get "Syntax error: default.html (61,43)" - with and without polyfills file.

**Comment by xcartmods** [comment]
It's almost working! ... to init I'm using...

`var menu = new MmenuLight(document.querySelector('#menu'), {
  // title: 'Menu',
  // theme: 'light',
  // selected: 'Selected'
});
menu.enable('all'); // '(max-width: 900px)'

menu.offcanvas({
  position: 'left',// [| 'right']
  move: true,// [| false]
  blockPage: true,// [| false | 'modal']
});

//	Open the menu.
document.querySelector('a[href="#menu"]').addEventListener('click', function (evnt) {
  menu.open(); // Don't forget to "preventDefault" and to "stopPropagation".
  evnt.preventDefault();
  evnt.stopPropagation();
});`

And I'm testing with this polyfill
`<script src="https://cdnjs.cloudflare.com/ajax/libs/dom4/2.0.0/dom4.js"></script>`

**Comment by FrDH** [comment]
> Unfortunately menu still does not work. Now I only get "Syntax error: default.html (61,43)" - with and without polyfills file.

Try if replacing the `const` with a `var` helps.

**Comment by FrDH** [comment]
> It's almost working! ... to init I'm using...

What part isn't working?

**Comment by xcartmods** [comment]
For me in IE11/Win7, it's showing the menu at all times (that's with the dom4.js polyfill)
If I don't use the dom4.js polyfill and use mmenu-light.polyfills.js I get this error...
Object doesn't support property or method 'after'

**Comment by stl-pl** [comment]
> Try if replacing the `const` with a `var` helps.

No change.

**Comment by FrDH** [comment]
> For me in IE11/Win7, it's showing the menu at all times

As per the Introduction of the latest CSS 2D Transforms draft, a transformed element creates a containing block for all its positioned descendants. This is why the sliding submenus can work without having to alter the DOM.
Only not in IE11... 
I'll see if I can introduce a fallback with vertically expanding submenus just for IE :/

> Try if replacing the `const` with a `var` helps.
> No change

You'll also need to convert the arrow function to a normal function:
````js
// turn this:
(event) => {
// into this:
function(event) {
````

Hope this helps.

**Comment by polycode-nz** [comment]
Is it your recommendation @FrDH that those of us using this light version and needing to support IE11 that we should wait for your changes above not fall back to an earlier version?

**Comment by stl-pl** [comment]
> You'll also need to convert the arrow function to a normal function:
> 
> ```js
> // turn this:
> (event) => {
> // into this:
> function(event) {
> ```

Now I get the same error as @xcartmods. Menu is open all the time, but it's broken. Menu fills the entire page, elements overlap, parent items stay on screen.

With dom4.js polyfills menu also fills the entire page but looks good and "sliding" works just fine.

**Comment by FrDH** [comment]
Please five version 2.3.0 a try.
It has an option "slidingSubmenus" that can be set to `false` (and for IE11 it is forced to being `false`).

**Comment by stl-pl** [comment]
Almost there. Element `ul.mm--open` is too wide so You can't see the arrows. The same thing happens with submenus. There are also errors:
- Object doesn't support this action: mmenu-light.js (1,4337) [after opening the menu]
- Object doesn't support this action: mmenu-light.js (1,4557) [after closing the menu]

**Comment by xcartmods** [comment]
This fixes v2.3.0 up a bit...
```@media all and (-ms-high-contrast: none), (-ms-high-contrast: active) {
    ul.mm--open { max-width: 100%; overflow-y: hidden; }
	ul.mm--open ul { max-width: 95%; }
	ul.mm--open ul ul { max-width: 90%; }
}```
And it's error free if you use this polyfill...
<script src="https://cdnjs.cloudflare.com/ajax/libs/dom4/2.0.0/dom4.js"></script>

**Comment by FrDH** [comment]
Does changing the with to `initial` work? I had it set to `unset`, but that might inherit.

````css
.mm.mm--vertical ul {
    width: initial;
}
````

The errors are probably due to the `dispatchEvent` method, I'll add a polyfill for that.

**Comment by xcartmods** [comment]
Sadly no Fred, maybe this might help you out?
https://www.browserling.com/internet-explorer-testing
I believe it's free to use, but there's a time limit on it.

**Comment by FrDH** [comment]
Too bad, I have access to browserstack, but am currently out of office :)

**Comment by xcartmods** [comment]
Bingo, v2.3.1 all good in IE11 !

**Comment by FrDH** [comment]
hurray :)

**Comment by polycode-nz** [comment]
FWIW: Yup - good for me too.

Cheers!
