### ISSUE TITLE
Modified touch position breaks website navigation with iOS

### ISSUE THREAD

**Issue by benoitchantre** [FrDH/mmenu-light#14]
Since version `2.1.0`, I have experienced a strange behaviour on the website: I was unable to follow links in the page. Trying to select some words, I noticed that the selection was much higher than my finger. After having disabled the initialization of the mobile menu, the website worked normally.

I rolled back to version `2.0.3` and this issue disappeared. Something has been introduced in verison `2.1.0`.

Notes:
- it is not possible to reproduce this behaviour a desktop browser, you need to use a real device
- with version `2.0.3`, an event handler placed on `body` doesn't get any click event when I close the menu

Tested with iOS 12.4, Safari and Firefox browsers

**Comment by FrDH** [comment]
Thanks for reporting the issue, hadn't noticed anything myself. In `2.1.0` an alternate approach fixed the click event bug.
I'll do some investigating.

**Comment by benoitchantre** [comment]
> I had a look at the example on the website (which uses 2.1.0) on iOS safari, iOS FireFox and iOS Chrome, but could not reproduce the issue. I was able to select text and follow links.
> 
> Is there an online (reduced) test case of the problem?

Thanks for your fast reply @FrDH. I can reproduce the issue with the link in your comment.

The issue is appears inside the page, when the menu is closed.
Try to select _This is a demo_. You will notice that you can't select it: the selection will be displayed much higher than under your finger.

**Comment by FrDH** [comment]
![EA87D40F-FE66-4232-966C-474CC1674254](https://user-images.githubusercontent.com/1387163/63515253-b2a41580-c4ea-11e9-8843-8959da685698.png)

What phone are you using? I’ll check on an iPad later on, but on my iPhone this worked as intended.

**Comment by benoitchantre** [comment]
> What phone are you using?

@FrDH I use an iPhone XR. I have also tested with an iPhone 8 and got the same issue.

**Comment by FrDH** [comment]
This is odd, I just had another look and now also experience this issue. I'll see what I can find and try to fix it.

**Comment by FrDH** [comment]
Try version 2.2.3, should fix the issue. Thanks for reporting it.

**Comment by benoitchantre** [comment]
@FrDH I just tested version 2.2.3.1 and cannot reproduce the issue. Thank you for the fix.
