### ISSUE TITLE
mmenu-light 3 and webpack

### ISSUE THREAD

**Issue by mhlozek** [FrDH/mmenu-light#16]
I try import mmenu light to my app where I compile all JS script by webpack.

`import MmenuLight from 'mmenu-light'` worked with old version (2.3.1), but it doesn't work with new mmenu light anymore. 
I get error "Module not found: Error: Can't resolve '../bin/core/index' in... "

How can I fix this?

**Comment by FrDH** [comment]
I removed the `bin` directory from the repo, but now realize I shouldn't have :|
I'll re-add it later on.

For now, If you're using typescript, you can import the .ts file, this probably is the cleanest way:
````js
import MmenuLight from 'mmenu-light/src/core/index';
````

**Comment by FrDH** [comment]
Try version 3.0.2

**Comment by mhlozek** [comment]
It's ok now. Thank you!
