### ISSUE TITLE
Typo in the docs

### ISSUE THREAD

**Issue by alljamin** [FrDH/mmenu-light#17]
History submenu item has an extra quotes - `<li"><a href="...">History</a></li>` - when it should be `<li><a href="...">History</a></li>`. I've spend some time trying to understand what is wrong with my code when I have found this issue.

<img width="942" alt="Screen Shot 2020-02-24 at 2 46 27 pm" src="https://user-images.githubusercontent.com/10956179/75128558-96d93080-5714-11ea-86e5-dc035c3e4e81.png">

**Comment by FrDH** [comment]
Thanks, I'll fix it shortly.
Sorry for the lost time :)
