### ISSUE TITLE
menu.querySelector is not a function

### ISSUE THREAD

**Issue by alljamin** [FrDH/mmenu-light#18]
Following `mmenu-light` API add-on invocation example resolves to the following error:

> menu.querySelector is not a function

Perhaps you can have a look what could be wrong with the example.

<img width="1047" alt="Screen Shot 2020-02-24 at 2 51 16 pm" src="https://user-images.githubusercontent.com/10956179/75128702-3e566300-5715-11ea-965b-63f5b5e6dfdc.png">

**Comment by FrDH** [comment]
Thanks (again), I'll update the docs shortly.
For now, you could use:
````js
document.querySelector("#my-menu ul");
````
or
````js
menu.menu.querySelector("ul");
````

Hope this helps.
