### ISSUE TITLE
wrong description in the documentation plugin-node

### ISSUE THREAD

**Issue by pvy** [FrDH/mmenu-light#19]
"Options for the plugin - node" has description belonging to "Options for the navigation add-on - theme"

![Snímek z 2020-02-28 14-01-27](https://user-images.githubusercontent.com/2955165/75551043-90f48f80-5a33-11ea-99ae-99aa69ed529e.png)

**Comment by FrDH** [comment]
Thanks, I'll fix it shortly.

**Comment by FrDH** [comment]
fixed it :)
