### ISSUE TITLE
Menu "flashing" while using back arrow

### ISSUE THREAD

**Issue by Voodoopupp** [FrDH/mmenu-light#2]
The whole menu is flashing blue when using the "back arrow".

Visible here (need to view it with a Smartphone):
https://mmenujs.com/demo/index.html?demo=mmlight

Open Menu, go down "About us" -> "The Team"
Now go back using the arrow on top of the menu
-> whole menu flashes blue

Diffent on the normal mmenu:
https://mmenujs.com/demo/index.html?demo=menu-advanced-2

Go deeper into the menu
By going up in the menu, only the arrow is flashing blue.

---------------------------------------------
Tested on two Android Smartphones.

**Comment by Voodoopupp** [comment]
I think its because the normale mmenu is divided into mm-navbar & mm-panels.

Any way to achieve "navbars" with the light version?

**Comment by FrDH** [comment]
I'll have to do some investigating.
Some small side notes:
- the example on the website uses version 1.0.1, could you check if the issue persists in version 1.0.4?
- the example on the website is inside an iframe, that almost always means buggy behavior on touch screens (I really need to find a workaround for this).

**Comment by Voodoopupp** [comment]
I am already using 1.0.4 on my testshop:
https://2000[dot]spuersinn24[dot]de

Also there you can see the same behaviour.

I have found a "solution", which will surpress this:
-webkit-tap-highlight-color: transparent;
got it from: https://stackoverflow.com/questions/21003535/anyway-to-prevent-the-blue-highlighting-of-elements-in-chrome-when-clicking-quic

Otherwise then you will loose all "feedback" of the click - this is also not exactly the best thing.
Best way is, if the header is divided from the panel, then only the header would "flash."

**Comment by FrDH** [comment]
Thanks, I tested on an iPhone (safari and chrome) but could not reproduce the issue, I'll add the solution (on what CSS selector did you add it?) and do some more testing on other devices.

**Comment by Voodoopupp** [comment]
Just for a test I added a separate CSS class.

So in example with your tutorial here (https://mmenujs.com/mmenu-light/tutorial.html
`<nav id="my-menu">`
was then
`<nav id="my-menu" class="xyz">`

**Comment by FrDH** [comment]
OK thanks,
Adding an element for the header would go agains the idea of not altering the HTML, so I guess I'll add the CSS to the entire menu and add some custom feedback for the click.

**Comment by FrDH** [comment]
I added the `-webkit-tab-highlight` fix in version 1.0.6
Could  you give it a try? I tested but got no flash in iOS (safari, chrome and ff)

**Comment by Voodoopupp** [comment]
Hi,

worked as expected ;)

Perfect!
