### ISSUE TITLE
Anchors and mmenu behaviour

### ISSUE THREAD

**Issue by bigfraggle** [FrDH/mmenu-light#21]
It's not a real issue... But when clicking on a link to an anchor, the menu doesn't disappear. In earlier releases this works proper.

Thanks!
Marc

**Comment by FrDH** [comment]
I dont think closing the menu when clicking an anchor link is generic enough to be the default behavior. 
I guess you could simply add an eventlistener to the anchors to close the menu, just make sure to do so BEFORE invoking the mmenu light plugin:
````js
const node = document.querySelector( "#my-menu" );

let drawer;

node.addEventListener("click", evnt => {
    const target = evnt.target;
    if (target.matches("a") && target.classList.includes("some-classname") ) {
        drawer.close();
    }
});

const menu = new MmenuLight(node);
const navigator = menu.navigation();
drawer = menu.offcanvas();
````

Haven't tested it, but something like this should do the trick I think.
Hope this helps.

**Comment by bigfraggle** [comment]
Thank you for your thoughts. :)

I'm not really familiar with javascript but I will have a look at your snippet.

Apart from this I do think that closing the menu when clicking an anchor link is very generic. At least I cannot spot a reason why the menu should be leaved open.

**Comment by FrDH** [comment]
Maybe because the link triggers a popup?
This way the behavior can be added when needed.

**Comment by bigfraggle** [comment]
The answer is a bit late, but unfortunately your code doesn't work for me. Maybe it's just that I have no idea what I'm even trying to do here...

Console says "SyntaxError: Unexpected token const".

What do you mean by "BEFORE invoking"? Does the code need to be included before including mmenu-light.js?

```
<script>
	document.addEventListener(
		const node = document.querySelector( "#my-menu" );

		let drawer;

		node.addEventListener("click", evnt => {
			const target = evnt.target;
			if (target.matches("a") && target.classList.includes("some-classname") ) {
			drawer.close();
			}
		});

		const menu = new MmenuLight(node);
		const navigator = menu.navigation();
		drawer = menu.offcanvas();
	);
</script>

<script src="mmenu/mmenu-light.js"></script>

<script>
	document.addEventListener(
		"DOMContentLoaded", () => {
			const menu = new MmenuLight(
				document.querySelector( "#my-menu" ),
				"(max-width: 1019px)"
			);
			const navigator = menu.navigation({
				title: "Page name",
				theme: "light"
			});
			const drawer = menu.offcanvas();
			document.querySelector( "a[href='#my-menu']" ) .addEventListener( "click", ( evnt ) => {
				evnt.preventDefault();
				drawer.open();
			});
		}
	);
</script>
```
