### ISSUE TITLE
Is there any method like onToggle for the menu.offcanvas()?

### ISSUE THREAD

**Issue by bfiessinger** [FrDH/mmenu-light#22]
I checked the code for some method like onToggle to create animations for the toggler when firing the close() or open() method but I did not find anything relevant for this. Am I missing something or is it just not possible at the moment?

**Comment by FrDH** [comment]
There are no callbacks or event for when the menu opens and closes, you could use a Mutation [Observer to observer](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver), something like this:

````js
const menu = new MmenuLight(
   document.querySelector( "#my-menu" ),
   "(max-width: 600px)"
);

menu.navigation();
menu.offcanvas();

const observer = new MutationObserver((mutationsList, observer) => {
    for(let mutation of mutationsList) {
        if (mutation.type === 'attributes' and mutation.attributeName === 'class') {
            console.log(document.body.classList.contains("mm-ocd-opened") ? "open" : "clsoe" );
        }
    }
});

observer.observe(document.body, { attributes: true });
````

Hope this helps.
