### ISSUE TITLE
Google Lighthouse: use passive touchstart eventListener

### ISSUE THREAD

**Issue by jonaseberle** [FrDH/mmenu-light#25]
Thank you for this light and wonderful menu!

In Google PageSpeed checks nowadays it is checked touch-events are registered passive. It [suggests to use](https://web.dev/uses-passive-event-listeners/) 

    document.addEventListener('touchstart', onTouchStart, {passive: true});

The background is that this can improve scroll performance.

I think we could use that here https://github.com/FrDH/mmenu-light/blob/master/src/modules/offcanvas-drawer/index.ts#L56 as we are not preventing the event. So if I understand it correctly we could use `passive`.

**Comment by FrDH** [comment]
Hi,
Thank you for bringing this to my attention, I’ll implement this shortly.

**Comment by FrDH** [comment]
Has been implemented in 3.0.4

**Comment by jonaseberle** [comment]
Thank you!
