### ISSUE TITLE
The close button is hidden when you open the menu

### ISSUE THREAD

**Issue by 4goodapp** [FrDH/mmenu-light#27]
Is there a way to let the close button visible?
It's not obvious users will know that they have to click outside of the menu to close it.

<img width="879" alt="Screen Shot 2020-06-21 at 03 12 56" src="https://user-images.githubusercontent.com/6249230/85215816-1e564980-b36d-11ea-928c-aa6ac78dcdd6.png">

**Comment by FrDH** [comment]
For now, not by default. I guess you could add a button to you HTML that you only show when the menu is opened (a classname is added to the `<body>`).
Hope this helps.

**Comment by 4goodapp** [comment]
Hopefully you can add this in next version as it makes more sense to open and close a menu with an open and close button respectively for a better user experience. :)

**Comment by srikat** [comment]
Here's how I solved this:

```
// add a close icon in div.mm-ocd__content
document.querySelector(".mm-ocd__content").insertAdjacentHTML(
"afterbegin",
`<div class="close-icon">
    <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 0 24 24" width="24px" fill="#000000"><path d="M0 0h24v24H0V0z" fill="none"/><path d="M19 6.41L17.59 5 12 10.59 6.41 5 5 6.41 10.59 12 5 17.59 6.41 19 12 13.41 17.59 19 19 17.59 13.41 12 19 6.41z"/></svg>
</div>`
);

// when button.close-icon is clicked, close the menu
document.querySelector(".close-icon").addEventListener("click", (e) => {
    drawer.close();
});
```
