### ISSUE TITLE
Have to double click icon in <a> to open the menu on ios?

### ISSUE THREAD

**Issue by twd3** [FrDH/mmenu-light#28]
I have no hover stuff going on but I have to tap twice to open menu on ios? Is this normal behavior or is there something I can do to make menu open with just one tap?

**Comment by FrDH** [comment]
Hi,

What if you don't put it in an `<a>` but a `<button>` or `<span>`?
If anything else fails, I guess you could replace the "click" event with  a "mousedown" and/or "touchstart" event.
