### ISSUE TITLE
How to use mmenu data -attribute?

### ISSUE THREAD

**Issue by shakibdshy** [FrDH/mmenu-light#29]

**Comment by FrDH** [comment]
You can set a `data-mm-spn-title` to each `<ul>`, if you don't the title will be fetched from the parent '<li>'.

**Comment by shakibdshy** [comment]
I mean ```data-mm-spn-title: "Menu", data-mm-spn-theme: dark, data-mm-spn-positioin: left/right,```. Can I add this attribute?

**Comment by FrDH** [comment]
Only the title for each `<ul>` can be set via the data attribute, all other options should be passed to the constructor.
