### ISSUE TITLE
ScrollBugFix also for mmenu light?

### ISSUE THREAD

**Issue by Voodoopupp** [FrDH/mmenu-light#3]
Hi,

would it be possible to implement the scrollBugFix also for mmenu light?

**Comment by FrDH** [comment]
Good idea, I'll have a look at it.
For now, have you tried this fix: https://github.com/FrDH/mmenu-light/issues/1

**Comment by Voodoopupp** [comment]
Sorry, totally overseen - although it is the only issue ^^

As i am not that firm with Javascript, I do not know exactly how and where to include this into my javascript.

Actually my javascript is looking like this:
```
<script>
document.addEventListener(
    "DOMContentLoaded", () => {
        const menu = mmlight( document.querySelector( "#mobile-menu" ) );
        menu.create( "(max-width: 706px)" );
        menu.init( "Selected" );

        document.querySelector( '.open-mobile-menu' )
            .addEventListener( 'click', ( evnt ) => {
                menu.open();

                evnt.preventDefault();
                evnt.stopPropagation();
            });
            
        document.querySelector( '.mm-closeitnow' )
            .addEventListener( 'click', ( evnt ) => {
                menu.close();

                evnt.preventDefault();
                evnt.stopPropagation();
            });
    }
);
</script>
```

**Comment by FrDH** [comment]
lol, the fix can't be implemented as there are no "open" and "clsoe" hooks to hook into.
I'll implement this in the next release.

**Comment by Voodoopupp** [comment]
Great to hear that ;)
