### ISSUE TITLE
onClose event handler

### ISSUE THREAD

**Issue by CrazyTim** [FrDH/mmenu-light#37]
It would be useful to have an `onClose` event handler. 

**Use case**: the button that shows the menu is a hamburger button icon. I change the state of the hamburger icon animation when the menu is shown, however I need to register an event for when user closes the menu so I can animate the hamburger button back.

**Comment by FrDH** [comment]
If it's CSS only, you could use the classname added to the body when the menu is opened:
````css
.hamburger {
  /* styles for a hambuger */
}
.mm-body--open .hamburger {
  /* styles for a cross */
}
````

If you also need some JS to be invoked, you could use a mutation observer to observe the classname:
https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver

**Comment by kush1960** [comment]
Thanks FrDH.. using that tip I have some working code for anyone that needs it...

`
const mutationObserver = new MutationObserver(callback)
mutationObserver.observe(document.body, { attributes: true, attributeOldValue: true, attributeFilter: ['class']  })

callback(mutationsList, observer) {
    console.log('Mutations:', mutationsList)
    console.log('Observer:', observer)
    mutationsList.forEach(mutation => {
        if (mutation.attributeName === 'class') {
            console.log(mutation.oldValue);
	    console.log(document.body.classList);
			
            if (mutation.oldValue.includes("mm-ocd-opened")) {
                drawer.close();
            }
        }
    })
}
`

**Comment by kush1960** [comment]
This is a great plugin but would be much better if we could have an event to know when the menu is closed. Appreciate you want to keep the light version light, but IMO this is quite an important for developers, and mmenu-light is definitely the version for developers.

**Comment by srikat** [comment]
I used this alternative:

```
document.querySelector(".mm-ocd__backdrop").addEventListener("click", (e) => {
    document.querySelector("button.hamburger").classList.toggle("is-active");
});
```
