### ISSUE TITLE
[FEATURE REQUEST] Menu Only Mode

### ISSUE THREAD

**Issue by MatthewKennedy** [FrDH/mmenu-light#38]
Is there a way or can you add a config option that disables all the the off-canvas draw creation and toggle listener?

This would add flexibility to use the menu solo inside a Bootstrap modal, or any 3rd party off canvas draw, or even create your own simple css draw hard coded in.

## Benefits

- More robust in single-page apps (Turbolinks friendly)
- More flexibility to use in 3rd party off canvas draw or modal for a pop-up style menu.

**Comment by MatthewKennedy** [comment]
https://youtu.be/ngf7uD1lfhk

**Comment by MatthewKennedy** [comment]
Already do-able

**Comment by Werbschaft** [comment]
The video doesn't work. How can this be done?
