### ISSUE TITLE
MmenuLight Not Defined

### ISSUE THREAD

**Issue by diywebsites** [FrDH/mmenu-light#40]
Hi,
  Maybe I am missing it in the documentation somewhere but I always seem to be getting the error "MmenuLight not defined". I have seen issues raised with this, but it's been for the main version. Do I need to define this somewhere? Since I have copied the demos and I still keep getting the error. 

Thanks.

**Comment by FrDH** [comment]
Did you include the "mmenu-light.js" file in your webpage?
Here's a tutorial: https://mmenujs.com/mmenu-light/tutorial.html

**Comment by diywebsites** [comment]
Hi yes I did along with the css file, is it defined there? I think the program may just be calling my js file before it, but I wanted to double check if I needed to redeclare it somewhere.

**Comment by diywebsites** [comment]
Hi I was right, somehow, it was loading my js file before the mmenujs file. Thanks.
