### ISSUE TITLE
Making html link # tag to open sub menus

### ISSUE THREAD

**Issue by roshen81** [FrDH/mmenu-light#41]
Hi, is there a way to make HTML hash link (i,e. <a href="#"> </a> ) open a submenu? In mmenu normal verison we were able to do it by adding sub menu id. ie. mm-1. 
i.e.

<li><a href="#"></a>
  <ul>
  <li>Item 1 </li>
  <li>Item 1 </li>
  <li>Item 1 </li>
  </ul>
</li>

**Comment by FrDH** [comment]
Only wat to do so is by replacing the `<a href="#">` with a `<span>`.
