### ISSUE TITLE
Menu title dimmed color

### ISSUE THREAD

**Issue by diywebsites** [FrDH/mmenu-light#47]
Hi, do you know how to remove the dimmed color of the menu title? I would really like it to have a pure white color, but it ends up looking very unattractive with the forced dimmed overlay on the title.  

![menu-dimmed](https://user-images.githubusercontent.com/70768736/108800393-5c91b180-7569-11eb-92e6-98183a1909b0.png)

**Comment by thagxt** [comment]
`.mm-spn.mm-spn--navbar:after { opacity: 1; }`
