### ISSUE TITLE
Feature Request: Decouple off canvas

### ISSUE THREAD

**Issue by julmot** [FrDH/mmenu-light#5]
For this light version of mmenu it would be a great addition to be able to decouple it from the off canvas. I have an existing off canvas and just would like to embed mmenu in a container, so only the actual sliding menu. Off canvas animations etc. are already in place, since I have things to be shown above and beyond the menu itself.

**Comment by FrDH** [comment]
good idea.

**Comment by FrDH** [comment]
Try the new version 1.1.0
Make sure to check out the documentation first as it is a bit different from the previous version:
````js
const node = document.querySelector( "#my-menu" );
const menu = new MmenuLight( node );

menu.enable( "(max-width: 600px)" );
menu.offcanvas();
````

**Comment by julmot** [comment]
I'm not so sure whether we did understand each other correctly. From what I can see the "ul" in both `mmenu-light.css` and `mmlight.css` still have

```css
  position:fixed;
  top:var(--mml-item-height);
  bottom:0;
  left:100%;
  width:100%;
```

therefore, it'll not `always be visible in its parent` (documentation), since position fixed will overlap any parent. So I think this option isn't really meant to be integrated into an existing off canvas. Or am I missing something?

**Comment by FrDH** [comment]
The menu itself (the `<nav />`) has a `transform`applied to it, that creates a new "viewport". In other words, the `<ul />` indeed is fixed positioned, but relative to the `<nav />`.
