### ISSUE TITLE
Mburger integration or equivalent

### ISSUE THREAD

**Issue by jigarius** [FrDH/mmenu-light#52]
I found `mmenu` while looking for a vanilla JS mobile menu library. I integrated `mmenu-light`, but it seems that `mburger` doesn't work with `mmenu-light`? If it is so, then I have 2 suggestions:

- Option 1: `mburger` should work with `mmenu-light` because the menu button will need to indicate that the menu is open.
- Option 2: `mmenu-light` could simply look for all anchors with a `href="#menu-id"` and give them a class, e.g., `mmenu-open`.
  - This will allow devs to style the button's `open` state with ease.

If a solution to this problem is already available, please let me know so that I can finish integrating this cool mobile menu on my website (and remove jQuery).

**Comment by FrDH** [comment]
You should have a look at using a mutation observer.
It could observe the menu for the classname `mm--open`.
