### ISSUE TITLE
Mmenu Light not appending original nav location in Safari

### ISSUE THREAD

**Issue by sawirricardo** [FrDH/mmenu-light#53]
<img width="609" alt="Screen Shot 2021-05-05 at 10 33 52" src="https://user-images.githubusercontent.com/37329575/117094222-69165f80-ad8d-11eb-91d1-1698c78d1f91.png">

I think it just happened in safari, but in Chrome it's working
<img width="514" alt="Screen Shot 2021-05-05 at 10 34 40" src="https://user-images.githubusercontent.com/37329575/117094259-864b2e00-ad8d-11eb-98bb-a5919dd5175d.png">
*Above in chrome. Working as expected.

Any ideas? May be due to the way safari handle JS differently? @FrDH 

Thank you

**Comment by sawirricardo** [comment]
<img width="514" alt="Screen Shot 2021-05-05 at 10 34 40" src="https://user-images.githubusercontent.com/37329575/117094857-1c338880-ad8f-11eb-9ca2-4252b47839f2.png">
The visual, as you can see, the menu is still there, when it should already prepended to the mm-ocd__content.

**Comment by sawirricardo** [comment]
The visual, as you can see, the menu is still there, when it should already prepended to the mm-ocd__content.
<img width="756" alt="Screen Shot 2021-05-05 at 10 46 03" src="https://user-images.githubusercontent.com/37329575/117094962-42592880-ad8f-11eb-8853-a2ded4ccae23.png">

**Comment by sawirricardo** [comment]
I've fixed it. Here is what I did.

`document.addEventListener('DOMContentLoaded',
                                function() {
                                    const menu = new MmenuLight(
                                        document.querySelector( "#mobile-menu" ),
                                        // "(max-width: 600px)" --> Please don't use this. This becomes an issue in Safari. (weirdly not in other browser)
                                        );
                                    const navigator = menu.navigation();
                                    const drawer = menu.offcanvas();

                                    document.getElementById('mobile-menu-button').addEventListener( "click", ( event ) => {
                                        event.preventDefault();
                                        drawer.open();
                                    });

                                    // Only in safari, if menu is not yet initialized,
                                    // document.querySelector('mm-ocd__coontent').appendChild(document.querySelector( "#mobile-menu" ))
                                    })`
                                    
But I think this worth to note. I think you should clarify this in the tutorial page https://mmenujs.com/mmenu-light/tutorial.html

**Comment by FrDH** [comment]
Maybe safari wasn't supporting the [MediaQueryList API: onchange](https://caniuse.com/mdn-api_mediaquerylist_onchange).
Appears to work now.
