### ISSUE TITLE
How to switch between a fixed navigator and off-canvas drawer

### ISSUE THREAD

**Issue by kehhf** [FrDH/mmenu-light#58]
Is there anyway to design a navbar shown in two ways? It will be shown as fixed navigator when screen is wider, and will be shown as off-canvas drawer when screen is narrow?
I have tried to use two menus:
  <script>
    function onready() {
      const        
      mmenuw = new mmenuLight(document.querySelector("#category"), "(min-width: 768px)"),
      navigatorw = mmenuw.navigation({ }),
      mmenun = new mmenuLight(document.querySelector("#category"), "(max-width: 767px)"),
      navigatorn = mmenun.navigation({ }),
      drawern = mmenun.offcanvas({});
      document.querySelector("a[href='#category']").addEventListener("click", (e) => { e.preventDefault(); drawern.open(); });
    }
    document.readyState == 'loading' ? document.addEventListener('DOMContentLoaded', onready, false) : onready();
  </script> 
But these are not working...

**Comment by FrDH** [comment]
Yes, try the `mediaQuery` option for the `offcanvas` method:
https://mmenujs.com/mmenu-light/tutorial.html
