### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by julmot** [FrDH/mmenu-light#6]
Where can I find the changelog of the two most recent versions? On the Github releases page, there's no description for the latest change which seems to be quite hughe from a files diff perspective.

**Comment by julmot** [comment]
It also seems like the dist file with the umd suffix isn't generated in v1.1.0 compared to v1.0.6, so actually this is a breaking change and from my opinion should have been a reason for v2.0.0.

[Reference](https://github.com/FrDH/mmenu-light/compare/v1.0.6...master)

**Comment by julmot** [comment]
It also seems like the `main` property in the `package.json` points to an invalid file. Within the `dist` folder there's no "mmenu.js" file, only "mmenu-light.js".

**Comment by julmot** [comment]
I think it would be worth providing a live example on the plugin's homepage to see off canvas / normal in action. It's very hard for me currently to get everything up and running, I don't think the new version is ready to be used for stable production environments. I can't even see children except for the root level in my app. Pasting the [tutorial code](https://mmenujs.com/mmenu-light/tutorial.html) into jsfiddle also doesn't seem to generate a proper example: [Fiddle](https://jsfiddle.net/z3oy0hbf/)

**Comment by julmot** [comment]
When scrolling, the new version doesn't seem to keep the border. So the border bottom of "Menu" will disappear when srolling. Couldn't see this on the website itself, does it use the most recent version?

Before scrolling:
![000122](https://user-images.githubusercontent.com/8310677/60288528-abaabd80-9914-11e9-9375-15c08f7d013d.png)

After scrolling:
![000121](https://user-images.githubusercontent.com/8310677/60288526-aa799080-9914-11e9-883e-5e0134d6dbae.png)

**Comment by FrDH** [comment]
one question per issue please

**Comment by julmot** [comment]
@FrDH Ok, I will consider this for the future. Would you mind to answer to the issues above?

**Comment by FrDH** [comment]
- There is no changelog as untill yesterday there were no changes. I'll add a changelog shortly. As this plugin in still in its infancy, big changes are unavoidable.
- I'll update the package.json (sorry for the inconvenience). The `main` property should point to the plain .js script, the `module` property should point to the module.
- I don't think I changed anything to the border, but I'll have a look.

**Comment by julmot** [comment]
Thanks for your reply.

> As this plugin in still in its infancy, big changes are unavoidable.

Please consider releasing a new major version if there are changes that will break an existing implementation:
https://semver.org/

**Comment by FrDH** [comment]
You're right
