### ISSUE TITLE
DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

### ISSUE THREAD

**Issue by gingapa** [FrDH/mmenu-light#66]
`Deprecation Warning: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($mmspn-item-height, 2)

More info and automated migrator: https://sass-lang.com/d/slash-div
       top: $mmspn_item_height / 2; // IE11 fallback
                 ^^^^^^^^^^^^^^^^^^^^^^
    node_modules/mmenu-light/src/modules/sliding-panels-navigation/_index.scss 143:12  @import
    node_modules/mmenu-light/src/mmenu-light.scss 13:9                                 @import`

**Comment by FrDH** [comment]
should be fixed in version 3.1.0

**Comment by RamakantSonkhedkar** [comment]
[11:53:25] Starting 'build:compile-css'...
Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($spacer, 2) or calc($spacer / 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

    ╷
298 │ $headings-margin-bottom:      $spacer / 2 !default;
    │                               ^^^^^^^^^^^
    ╵
    build\_css\clay\bootstrap\_variables.scss 298:31  @import
    build\_css\clay\bootstrap\bootstrap.scss 9:9      @import
    build\_css\clay\base.scss 7:9                     @import
    build\_css\clay.scss 1:9                          root stylesheet

Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($input-padding-y, 2) or calc($input-padding-y / 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

    ╷
493 │ $input-height-inner-quarter:            calc(#{$input-line-height * .25em} + #{$input-padding-y / 2}) !default;
    │                                                                                ^^^^^^^^^^^^^^^^^^^^
    ╵
    build\_css\clay\bootstrap\_variables.scss 493:80  @import
    build\_css\clay\bootstrap\bootstrap.scss 9:9      @import
    build\_css\clay\base.scss 7:9                     @import
    build\_css\clay.scss 1:9                          root stylesheet

Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($custom-control-indicator-size, 2) or calc($custom-control-indicator-size / 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

    ╷
560 │ $custom-switch-indicator-border-radius:         $custom-control-indicator-size / 2 !default;
    │                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
    build\_css\clay\bootstrap\_variables.scss 560:49  @import
    build\_css\clay\bootstrap\bootstrap.scss 9:9      @import
    build\_css\clay\base.scss 7:9                     @import
    build\_css\clay.scss 1:9                          root stylesheet

Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($spacer, 2) or calc($spacer / 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

    ╷
706 │ $nav-divider-margin-y:              $spacer / 2 !default;
    │                                     ^^^^^^^^^^^
    ╵
    build\_css\clay\bootstrap\_variables.scss 706:37  @import
    build\_css\clay\bootstrap\bootstrap.scss 9:9      @import
    build\_css\clay\base.scss 7:9                     @import
    build\_css\clay.scss 1:9                          root stylesheet

Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($spacer, 2) or calc($spacer / 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

    ╷
711 │ $navbar-padding-y:                  $spacer / 2 !default;
    │                                     ^^^^^^^^^^^
    ╵
    build\_css\clay\bootstrap\_variables.scss 711:37  @import
    build\_css\clay\bootstrap\bootstrap.scss 9:9      @import
    build\_css\clay\base.scss 7:9                     @import
    build\_css\clay.scss 1:9                          root stylesheet

[11:53:29] 'build:compile-css' errored after 3.58 s
[11:53:29] Error in plugin "sass"
Message:
    build\_css\compat\components\_dropdowns.scss
Error: compound selectors may no longer be extended.
Consider `@extend .dropdown-item, .disabled` instead.
See http://bit.ly/ExtendCompound for details.

   ╷
29 │         @extend .dropdown-item.disabled;
   │                 ^^^^^^^^^^^^^^^^^^^^^^^
   ╵
  build\_css\compat\components\_dropdowns.scss 29:11  root stylesheet
Details:
    formatted: Error: compound selectors may no longer be extended.
Consider `@extend .dropdown-item, .disabled` instead.
See http://bit.ly/ExtendCompound for details.

   ╷
29 │         @extend .dropdown-item.disabled;
   │                 ^^^^^^^^^^^^^^^^^^^^^^^
   ╵
  build\_css\compat\components\_dropdowns.scss 29:11  root stylesheet
    line: 29
    column: 11
    file: D:\Git_Repo\Erasmith_Repo\Liferay-Theme-Workspace\themes\erasmith-theme\build\_css\compat\components\_dropdowns.scss
    status: 1
    messageFormatted: build\_css\compat\components\_dropdowns.scss
Error: compound selectors may no longer be extended.
Consider `@extend .dropdown-item, .disabled` instead.
See http://bit.ly/ExtendCompound for details.

   ╷
29 │         @extend .dropdown-item.disabled;
   │                 ^^^^^^^^^^^^^^^^^^^^^^^
   ╵
  build\_css\compat\components\_dropdowns.scss 29:11  root stylesheet
    messageOriginal: compound selectors may no longer be extended.
Consider `@extend .dropdown-item, .disabled` instead.
See http://bit.ly/ExtendCompound for details.

   ╷
29 │         @extend .dropdown-item.disabled;
   │                 ^^^^^^^^^^^^^^^^^^^^^^^
   ╵
  build\_css\compat\components\_dropdowns.scss 29:11  root stylesheet
    relativePath: build\_css\compat\components\_dropdowns.scss
    domainEmitter: [object Object]
    domainThrown: false

[11:53:29] 'build' errored after 9.13 s
