### ISSUE TITLE
Example of how to use in an ES6 script

### ISSUE THREAD

**Issue by tacman** [FrDH/mmenu-light#71]
I'm  sure there's a very easy answer to this, but I'm stuck.

I've installed this

```bash
yarn add mmenu-light --dev
```

But when I try to fire it, I get an error that .enable() is not a function.

![image](https://user-images.githubusercontent.com/619585/160174415-31841164-920a-4435-99e3-2e33dc1cc6fc.png)

```javascript
// import { MmenuLight } from "mmenu-light";
// require('mmenu-light');
import 'mmenu-light';

        const menu = new MmenuLight( document.getElementById( "menu" ) );
        console.log(menu);

        menu.enable( "all" );
        menu.offcanvas();

```

I've left my attempts to load the plugin as comments, but none of them work.  Is there another way to fire it on a DOM element without a constructor?  It seems that most of the examples have the javascript within the HTML page, perhaps you could add one for a just javascript. 

Thanks.

**Comment by tacman** [comment]
I think I must have confused some instructions with the light version and the regular version...

**Comment by jgmdigital** [comment]
Hi @tacman did you manage to resolve your issue in the end?

Can you possibly help shed any light on this? https://github.com/FrDH/mmenu-light/issues/77

**Comment by tacman** [comment]
No, I gave up, but am still interested in a solution. I wanted to add a stimulus wrapper around it, to make it really easy to instantiate.
