### ISSUE TITLE
Desktop menu alternative

### ISSUE THREAD

**Issue by andimg93** [FrDH/mmenu-light#74]
Hello,
first of all mmenu is mainly mobile menu focused like the first m in the name? However did you thought about adding a desktop version of it? So that out of the box you get the desktop version on bigger sized screens and the known/familiar one on mobile/tablet devices.

I thought about a stripe like menu or something like that, a smooth animation with dropdowns.

For mobile is mmenu already the best possible plugin to use :-)

**Comment by FrDH** [comment]
For desktop, there are just too many different styles to make a single plugin.
