### ISSUE TITLE
Question regarding the license

### ISSUE THREAD

**Issue by mrpsiho** [FrDH/mmenu-light#79]
Hi,

I would like to clarify this: can I include your script into my site builder application? Users of the site builder may or may not use it. They decide. Also they may use it for personal and/or commercial projects. I never know this.

By "include in my builder" I mean I create a web component for using it inside the builder and working properly overall. The main part of that web component would be your script. In the documentation I write the name of the script used, version, links to API (if available) etc.

**Comment by FrDH** [comment]
Hi,
Thank you for asking.

You would need a "multiple website license" for this to automatically cover all future usage of your component.

You could also tell each of your customers they need to purchase a "single website license", but if were me, I'd save myself the hassle :)

**Comment by mrpsiho** [comment]
@FrDH 
Thanks for the answer and for the great product!
I have just spotted that `mmenu-light` is licensed differently than `mmenu` and can be used for commercial use.
