### ISSUE TITLE
$prefix scss variable clashes with Bootstrap's $prefix variable

### ISSUE THREAD

**Issue by xewl** [FrDH/mmenu-light#81]
```
$prefix: ".mm-ocd";
```

offcanvas-drawer module

**Comment by FrDH** [comment]
Thank you for bringing this to my attention, I might change the variable name in the future. For now I'd suggest not to combine the two in a single build.

**Comment by xewl** [comment]
We just moved it to the end of the file, so nothing in-between clashes. Renaming it to `$mmocd_prefix` would definitely help :)

**Comment by FrDH** [comment]
changed it in 3.2.2
thanks.
